# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 05:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix', models.CharField(blank=True, max_length=32, null=True)),
                ('char_name', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('color', models.CharField(blank=True, max_length=6, null=True)),
                ('week', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CharStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.SmallIntegerField()),
                ('pic', models.CharField(blank=True, max_length=256)),
                ('pronouns', models.CharField(choices=[('M', 'He/Him'), ('F', 'She/Her'), ('N', 'They/Them')], max_length=1)),
                ('role', models.CharField(default='Unknown', max_length=32)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('bio', models.CharField(blank=True, max_length=1000, null=True)),
                ('fee', models.CharField(blank=True, max_length=1000, null=True)),
                ('reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('personality', models.CharField(blank=True, max_length=1000, null=True)),
                ('appearance', models.CharField(blank=True, max_length=1000, null=True)),
                ('yen', models.IntegerField(default=0)),
                ('brv', models.SmallIntegerField(default=10)),
                ('pp', models.SmallIntegerField(default=0)),
                ('sync', models.SmallIntegerField(default=75)),
                ('curr_hp', models.SmallIntegerField(default=500)),
                ('base_hp', models.SmallIntegerField(default=500)),
                ('base_atk', models.SmallIntegerField(default=10)),
                ('base_def', models.SmallIntegerField(default=0)),
                ('misc_hp', models.SmallIntegerField(default=0)),
                ('misc_atk', models.SmallIntegerField(default=0)),
                ('misc_def', models.SmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='shibuyasgame.CharProfile')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='shibuyasgame.CharProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('heal', models.SmallIntegerField(default=0)),
                ('bonus_hp', models.SmallIntegerField(default=0)),
                ('bonus_atk', models.SmallIntegerField(default=0)),
                ('bonus_def', models.SmallIntegerField(default=0)),
                ('req_mod', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('is_equipped', models.BooleanField(default=False)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='shibuyasgame.CharStats')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=10000)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=128)),
                ('atk', models.SmallIntegerField()),
                ('eff', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=32)),
                ('booster', models.BooleanField(default=False)),
                ('req_mod', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('curr_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_stock', to='shibuyasgame.Item')),
                ('max_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where_stock', to='shibuyasgame.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=128)),
                ('thread_type', models.CharField(choices=[('A', 'Accessory'), ('T', 'Top'), ('TB', 'Top & Bottom'), ('B', 'Bottom'), ('H', 'Headwear'), ('F', 'Footwear'), ('M', 'Misc')], max_length=2)),
                ('base_hp', models.SmallIntegerField(default=0)),
                ('base_atk', models.SmallIntegerField(default=0)),
                ('base_def', models.SmallIntegerField(default=0)),
                ('eff', models.CharField(max_length=128)),
                ('bonus_condition', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary'), ('0', 'None')], default='0', max_length=1)),
                ('bonus_hp', models.SmallIntegerField(default=0)),
                ('bonus_atk', models.SmallIntegerField(default=0)),
                ('bonus_def', models.SmallIntegerField(default=0)),
                ('brv', models.PositiveIntegerField(default=10)),
                ('req_mod', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TradeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yen', models.PositiveIntegerField(default=0)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='shibuyasgame.Item')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_recipient', to='shibuyasgame.CharProfile')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_giver', to='shibuyasgame.CharProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('N', 'None'), ('R', 'Reaper'), ('O', 'Officer'), ('TR', 'Tutorial Reaper'), ('GM', 'Game Master'), ('CN', 'Conductor'), ('CM', 'Conmposer'), ('P', 'Producer'), ('A', 'Accompanist')], default='N', max_length=2)),
                ('age', models.CharField(blank=True, max_length=30, null=True)),
                ('bio', models.CharField(blank=True, max_length=1000, null=True)),
                ('loc', models.CharField(blank=True, max_length=100, null=True)),
                ('skype', models.CharField(blank=True, max_length=100, null=True)),
                ('blog', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', timezone_field.fields.TimeZoneField(default='US/Eastern')),
                ('pic', models.CharField(blank=True, max_length=256)),
                ('is_shopkeep', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='owners',
            field=models.ManyToManyField(related_name='shops', to='shibuyasgame.UserProfile'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='shibuyasgame.UserProfile'),
        ),
        migrations.AddField(
            model_name='modrequest',
            name='handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handled', to='shibuyasgame.UserProfile'),
        ),
        migrations.AddField(
            model_name='modrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='shibuyasgame.UserProfile'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='perp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='shibuyasgame.UserProfile'),
        ),
        migrations.AddField(
            model_name='charprofile',
            name='mun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='shibuyasgame.UserProfile'),
        ),
    ]
