# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shibuyasgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
