# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shibuyasgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='evo',
            field=models.ManyToManyField(blank=True, null=True, to='shibuyasgame.Pin'),
        ),
        migrations.AlterField(
            model_name='charstats',
            name='partner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='shibuyasgame.CharProfile'),
        ),
        migrations.AlterField(
            model_name='charstats',
            name='role',
            field=models.CharField(default='', max_length=32),
        ),
    ]
