# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shibuyasgame', '0002_auto_20170507_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='evo',
            field=models.ManyToManyField(blank=True, related_name='evo_from', to='shibuyasgame.Pin'),
        ),
    ]
