# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shibuyasgame', '0006_auto_20170328_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='equipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='charstats',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='charstats',
            name='base_atk',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='charstats',
            name='base_def',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charstats',
            name='base_hp',
            field=models.SmallIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='charstats',
            name='brv',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='charstats',
            name='misc_atk',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charstats',
            name='misc_def',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charstats',
            name='misc_hp',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charstats',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='shibuyasgame.CharProfile'),
        ),
        migrations.AlterField(
            model_name='charstats',
            name='pp',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charstats',
            name='sync',
            field=models.SmallIntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='charstats',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='charstats',
            name='yen',
            field=models.IntegerField(default=0),
        ),
    ]
