# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shibuyasgame', '0011_auto_20170328_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charstats',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='charstats',
            old_name='visible',
            new_name='is_visible',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='equipped',
            new_name='is_equipped',
        ),
        migrations.AddField(
            model_name='charstats',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
