# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shibuyasgame', '0012_auto_20170328_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='bonus_atk',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='bonus_def',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='bonus_hp',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='heal',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='req_mod',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pin',
            name='req_mod',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='base_atk',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thread',
            name='base_def',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thread',
            name='base_hp',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thread',
            name='bonus_atk',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thread',
            name='bonus_condition',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary'), ('0', 'None')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='thread',
            name='bonus_def',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thread',
            name='bonus_hp',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thread',
            name='req_mod',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shibuyasgame.Item'),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='yen',
            field=models.IntegerField(default=0),
        ),
    ]
