# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shibuyasgame', '0013_auto_20170411_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.AddField(
            model_name='charstats',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='shibuyasgame.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
