# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shibuyasgame', '0016_auto_20170428_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='shibuyasgame.CharStats'),
        ),
    ]
