# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 04:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('color', models.CharField(blank=True, max_length=6, null=True)),
                ('pic', models.CharField(blank=True, max_length=256)),
                ('pronouns', models.CharField(choices=[('M', 'He/Him'), ('F', 'She/Her'), ('N', 'They/Them')], max_length=1)),
                ('role', models.CharField(choices=[('S', 'Support Reaper'), ('A', 'Active Reaper'), ('O', 'Officer'), ('TR', 'Tutorial Reaper'), ('GM', 'Game Master'), ('CN', 'Conductor'), ('CM', 'Conmposer')], max_length=2)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('bio', models.CharField(blank=True, max_length=1000, null=True)),
                ('fee', models.CharField(blank=True, max_length=1000, null=True)),
                ('reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('prsonality', models.CharField(blank=True, max_length=1000, null=True)),
                ('appearance', models.CharField(blank=True, max_length=1000, null=True)),
                ('yen', models.IntegerField()),
                ('brv', models.SmallIntegerField()),
                ('pp', models.SmallIntegerField()),
                ('sync', models.SmallIntegerField()),
                ('base_hp', models.SmallIntegerField()),
                ('base_atk', models.SmallIntegerField()),
                ('base_def', models.SmallIntegerField()),
                ('misc_hp', models.SmallIntegerField()),
                ('misc_atk', models.SmallIntegerField()),
                ('misc_def', models.SmallIntegerField()),
                ('visible', models.BooleanField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('heal', models.SmallIntegerField()),
                ('bonus_hp', models.SmallIntegerField()),
                ('bonus_atk', models.SmallIntegerField()),
                ('bonus_def', models.SmallIntegerField()),
                ('req_mod', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('P', 'Pin'), ('T', 'Thread'), ('F', 'Food')], max_length=1)),
                ('item_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shibuyasgame.CharProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('atk', models.SmallIntegerField()),
                ('eff', models.CharField(max_length=128)),
                ('req_mod', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('thread_type', models.CharField(choices=[('A', 'Accessory'), ('T', 'Top'), ('TB', 'Top & Bottom'), ('B', 'Bottom'), ('H', 'Headwear'), ('F', 'Footwear'), ('M', 'Misc')], max_length=2)),
                ('base_hp', models.SmallIntegerField()),
                ('base_atk', models.SmallIntegerField()),
                ('base_def', models.SmallIntegerField()),
                ('eff', models.CharField(max_length=128)),
                ('bonus_condition', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary'), ('0', 'None')], max_length=1)),
                ('bonus_hp', models.SmallIntegerField()),
                ('bonus_atk', models.SmallIntegerField()),
                ('bonus_def', models.SmallIntegerField()),
                ('req_mod', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TradeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yen', models.IntegerField()),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shibuyasgame.Item')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='shibuyasgame.CharProfile')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giver', to='shibuyasgame.CharProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(blank=True, max_length=30, null=True)),
                ('bio', models.CharField(blank=True, max_length=1000, null=True)),
                ('loc', models.CharField(blank=True, max_length=100, null=True)),
                ('skype', models.CharField(blank=True, max_length=100, null=True)),
                ('blog', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('pic', models.CharField(blank=True, max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shibuyasgame.UserProfile'),
        ),
        migrations.AddField(
            model_name='charprofile',
            name='mun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shibuyasgame.UserProfile'),
        ),
        migrations.AddField(
            model_name='charprofile',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shibuyasgame.CharProfile'),
        ),
    ]
