# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shibuyasgame', '0001_squashed_0021_auto_20170507_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='brand',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='pin',
            name='code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete='id', to='shibuyasgame.UserProfile', to_field='posts'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='US/Eastern'),
        ),
    ]
