# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shibuyasgame', '0002_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('N', 'None'), ('O', 'Officer'), ('TR', 'Tutorial Reaper'), ('GM', 'Game Master'), ('CN', 'Conductor'), ('CM', 'Conmposer')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='charprofile',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='charprofile',
            name='last_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='charprofile',
            name='role',
            field=models.CharField(default='Unknown', max_length=32),
        ),
    ]
