# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shibuyasgame', '0003_auto_20170327_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.SmallIntegerField()),
                ('pic', models.CharField(blank=True, max_length=256)),
                ('pronouns', models.CharField(choices=[('M', 'He/Him'), ('F', 'She/Her'), ('N', 'They/Them')], max_length=1)),
                ('role', models.CharField(default='Unknown', max_length=32)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('bio', models.CharField(blank=True, max_length=1000, null=True)),
                ('fee', models.CharField(blank=True, max_length=1000, null=True)),
                ('reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('prsonality', models.CharField(blank=True, max_length=1000, null=True)),
                ('appearance', models.CharField(blank=True, max_length=1000, null=True)),
                ('yen', models.IntegerField()),
                ('brv', models.SmallIntegerField()),
                ('pp', models.SmallIntegerField()),
                ('sync', models.SmallIntegerField()),
                ('base_hp', models.SmallIntegerField()),
                ('base_atk', models.SmallIntegerField()),
                ('base_def', models.SmallIntegerField()),
                ('misc_hp', models.SmallIntegerField()),
                ('misc_atk', models.SmallIntegerField()),
                ('misc_def', models.SmallIntegerField()),
                ('visible', models.BooleanField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='active',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='appearance',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='base_atk',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='base_def',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='base_hp',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='brv',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='misc_atk',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='misc_def',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='misc_hp',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='pp',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='pronouns',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='prsonality',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='sync',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='visible',
        ),
        migrations.RemoveField(
            model_name='charprofile',
            name='yen',
        ),
        migrations.AddField(
            model_name='charprofile',
            name='char_name',
            field=models.CharField(default='No Name', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='charstats',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character', to='shibuyasgame.CharProfile'),
        ),
        migrations.AddField(
            model_name='charstats',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='shibuyasgame.CharProfile'),
        ),
    ]
