# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shibuyasgame', '0004_auto_20170327_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='charstats',
            name='req_mod',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
