# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shibuyasgame', '0008_charprofile_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='charstats',
            name='curr_hp',
            field=models.SmallIntegerField(default=500),
        ),
    ]
