# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shibuyasgame', '0009_charstats_curr_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_shopkeep',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('N', 'None'), ('R', 'Reaper'), ('O', 'Officer'), ('TR', 'Tutorial Reaper'), ('GM', 'Game Master'), ('CN', 'Conductor'), ('CM', 'Conmposer')], default='N', max_length=2),
        ),
    ]
