# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shibuyasgame', '0010_auto_20170328_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('N', 'None'), ('R', 'Reaper'), ('O', 'Officer'), ('TR', 'Tutorial Reaper'), ('GM', 'Game Master'), ('CN', 'Conductor'), ('CM', 'Conmposer'), ('P', 'Producer'), ('A', 'Accompanist')], default='N', max_length=2),
        ),
    ]
