# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shibuyasgame', '0015_auto_20170428_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charstats',
            name='inventory',
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='shibuyasgame.CharStats'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
