# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shibuyasgame', '0018_thread_brv'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=10000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('perp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shibuyasgame.UserProfile')),
            ],
        ),
    ]
