# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shibuyasgame', '0019_logentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handled', to='shibuyasgame.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='shibuyasgame.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('curr_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_stock', to='shibuyasgame.Item')),
                ('max_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where_stock', to='shibuyasgame.Item')),
                ('owners', models.ManyToManyField(related_name='shops', to='shibuyasgame.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='charprofile',
            name='mun',
            field=models.ForeignKey(on_delete='id', to='shibuyasgame.UserProfile', related_name='characters'),
        ),
        migrations.AlterField(
            model_name='charstats',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='shibuyasgame.CharProfile'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='perp',
            field=models.ForeignKey(on_delete='id', to='shibuyasgame.UserProfile', related_name='log_entries'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete='id', to='shibuyasgame.UserProfile', related_name='posts'),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='shibuyasgame.Item'),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_recipient', to='shibuyasgame.CharProfile'),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_giver', to='shibuyasgame.CharProfile'),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='yen',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
